spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
      # port: 27017
       #host: mongo-container
       #database: SBA
  application:
    name: gipher-recommandation
  zipkin:
    base-url: http://localhost:9411/  
    locator:
      discovery:
        enabled: true
 

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
spring.sleuth.sampler.probability: 1