image: 'maven:3-jdk-8'
stages:
  - test
  - build
services:
  - 'mysql:5.5'
  - 'mongo:3.6'
variables:
  MYSQL_DATABASENAME: 'SBA'
  MYSQL_HOST: 'mysql'
  MYSQL_URL: "jdbc:mysql://localhost:3306/sba?createDatabaseIfNotExist=true"
  MYSQL_ROOT_PASSWORD: 'root'
  MYSQL_USERNAME: 'root'
  MYSQL_PASSWORD: 'root'
  MONGO_DATABASE: 'SBA'
  MONGO_HOST: 'mongo'
  MONGO_PORT: '27017'
cache:
  paths:
    - .m2/repository
    -  target
maven-test:
  stage: test
  script: "mvn test"
maven-build:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
