#spring:
  #datasource:
   # url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASENAME}
   # username: ${MYSQL_USER}
    #password: ${MYSQL_PASSWORD}
    # url: jdbc:mysql://localhost:3306/SBA?useSSL=false&allowPublicKeyRetrieval=true
   # url: jdbc:mysql://mysql-container:3306/SBA?useSSL=false&allowPublicKeyRetrieval=true
   # username: root
   # password: password
  #jpa:
   # hibernate:
    #  ddl-auto: update
    #show-sql: true
  #application:
   # name: user-auth
  #zipkin:
   # base-url: http://localhost:9411/  
    #locator:
     # discovery:
      #  enabled: true
      
#server:
 # port: 9200
#eureka:
 # client:
  #  service-url:
   #   default-zone: http://localhost:8761/eureka
    #  register-with-eureka: true
     # etch-registry: true
      
#spring.sleuth.sampler.probability: 1
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 
